# -*- coding: utf-8 -*-
"""DeepSeek-Medical_FineTuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CchPQVGT42KNMPO1MZ35r7MWujI-axhV
"""

!pip install unsloth # install unsloth
!pip install --force-reinstall --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth.git # Also get the latest version Unsloth!

from unsloth import FastLanguageModel
import torch
from trl import SFTTrainer
from huggingface_hub import login
from transformers import TrainingArguments
import wandb
from datasets import load_dataset

from google.colab import userdata
hf_token = userdata.get("HF_TOKEN")
login(hf_token)

print("CUDA available:", torch.cuda.is_available())
print("GPU device:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

#Loading The Model

import os

os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "0"
os.environ["HF_HUB_DISABLE_PROGRESS_BARS"] = "1"
os.environ["HF_ENDPOINT"] = "https://hf-mirror.com"

model_name = "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
load_in_4bit = True
dtype = None
max_sequence_length = 2048

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_name,
    max_seq_length = max_sequence_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    token = hf_token,

    trust_remote_code = True,
    rope_scaling = {"type": "linear", "factor": 1.0}
)

import os
os.environ["HF_HUB_DOWNLOAD_TIMEOUT"] = "600"

# Step6: Setup system prompt
prompt_style = """
Below is a task description along with additional context provided in the input section. Your goal is to provide a well-reasoned response that effectively addresses the request.

Before crafting your answer, take a moment to carefully analyze the question. Develop a clear, step-by-step thought process to ensure your response is both logical and accurate.

### Task:
You are a medical expert specializing in clinical reasoning, diagnostics, and treatment planning. Answer the medical question below using your advanced knowledge.

### Query:
{}

### Answer:
{}
"""

# Step7: Run Inference on the model

# Define a test question
question = """A 61-year-old woman with a long history of involuntary urine loss during activities like coughing or
              sneezing but no leakage at night undergoes a gynecological exam and Q-tip test. Based on these findings,
              what would cystometry most likely reveal about her residual volume and detrusor contractions?"""

FastLanguageModel.for_inference(model)

inputs = tokenizer([prompt_style.format(question, "")], return_tensors = "pt").to("cuda")

outputs = model.generate(
    input_ids = inputs.input_ids,
    attention_mask = inputs.attention_mask,
    max_new_tokens = 1500,
    use_cache = True
)

response = tokenizer.batch_decode(outputs)
print(response[0].split("### Answer:")[1])

#Loading dataset:

medical_dataset = load_dataset("FreedomIntelligence/medical-o1-reasoning-SFT", "en", split = "train[:500]", trust_remote_code = True)

medical_dataset.info

medical_dataset[1]

EOS_TOKEN = tokenizer.eos_token
EOS_TOKEN

### Finetuning
# Updated training prompt style to add  tag
train_prompt_style = """Below is an instruction that describes a task, paired with an input that provides further context.
Write a response that appropriately completes the request.
Before answering, think carefully about the question and create a step-by-step chain of thoughts to ensure a logical and accurate response.

### Instruction:
You are a medical expert with advanced knowledge in clinical reasoning, diagnostics, and treatment planning.
Please answer the following medical question.

### Question:
{}

### Response:

{}

{}"""

#preparing the data:

def preprocess_input_data(samples):
  inputs = samples['Question']
  cot = samples['Complex_CoT']
  outputs = samples["Response"]

  texts = []

  for inputs, cot, outputs in zip(inputs, cot, outputs):
    text = train_prompt_style.format(inputs, cot, outputs) + EOS_TOKEN
    texts.append(text)

  return texts



finetune_dataset = medical_dataset.map(preprocess_input_data, batched = True)

finetune_dataset.column_names

finetune_dataset["texts"][0]

# Apply LORA to the model:

model_lora = FastLanguageModel.get_peft_model(
    model = model,
    r = 16,
    target_modules = [
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj"
    ],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = 'none',
    use_gradient_checkpointing  = "unsloth",
    use_rslora = False,
    loftq_config = None,
    random_state = 3047
)

if hasattr(model, '_unwrapped_old_generate'):
    del model._unwrapped_old_generate

from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model = model_lora,
    tokenizer = tokenizer,
    train_dataset = medical_dataset,
    formatting_func = preprocess_input_data,
    dataset_text_field = "texts",
    max_seq_length = max_sequence_length,
    dataset_num_proc = 1,

    # Define training args
    args = TrainingArguments(
        per_device_train_batch_size = 1,
        gradient_accumulation_steps = 4,
        num_train_epochs = 1,
        warmup_steps = 5,
        max_steps = 60,
        learning_rate = 2e-4,
        gradient_checkpointing = True,
        fp16 = not is_bfloat16_supported(),
        bf16=is_bfloat16_supported(),
        logging_steps = 10,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type="linear",
        seed=3407,
        output_dir = "outputs",
    ),
)

# Setup WANDB
from google.colab import userdata
wnb_token = userdata.get("WAND_TOKEN")
# Login to WnB
wandb.login(key=wnb_token) # import wandb
run = wandb.init(
    project='Fine-tune-DeepSeek-R1-on-Medical-CoT-Dataset',
    job_type="training",
    anonymous="allow"
)

trainer_stas = trainer.train()

wandb.finish()

# Step10: Testing after fine-tuning
question = """A 61-year-old woman with a long history of involuntary urine loss during activities like coughing or sneezing
              but no leakage at night undergoes a gynecological exam and Q-tip test. Based on these findings,
              what would cystometry most likely reveal about her residual volume and detrusor contractions?"""

FastLanguageModel.for_inference(model_lora)

inputs = tokenizer(prompt_style.format(question, ""), return_tensors = "pt").to("cuda")

outputs = model_lora.generate(
    input_ids = inputs.input_ids,
    attention_mask = inputs.attention_mask,
    max_new_tokens = 1500,
    use_cache = True
)

response = tokenizer.batch_decode(outputs)
print(response)

print(response[0].split("### Answer:")[1])

